# Generated by Django 4.2.9 on 2024-04-30 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_default_country_profile_default_county_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('symbol', models.ImageField(blank=True, null=True, upload_to='allergens/')),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='allergen_preferences',
        ),
        migrations.AddField(
            model_name='profile',
            name='allergen_preferences',
            field=models.ManyToManyField(blank=True, to='profiles.allergen'),
        ),
    ]
