# Generated by Django 4.2.9 on 2024-05-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_subscriptionproduct_profile_subscription_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='newsletter_recipient',
            field=models.BooleanField(default=True),
        ),
    ]
