# Generated by Django 4.2.9 on 2024-04-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_allergen_remove_profile_allergen_preferences_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='shipping_address',
        ),
        migrations.AddField(
            model_name='profile',
            name='newsletter_recipient',
            field=models.BooleanField(default=False),
        ),
    ]
