# Generated by Django 4.2.9 on 2024-05-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_newsletter_recipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dietary_preference',
            field=models.CharField(choices=[('none', 'None'), ('plant_based', 'Plant Based')], default='none', max_length=20),
        ),
    ]
