# Generated by Django 4.2.9 on 2024-05-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_remove_profile_billing_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dietary_preference',
            field=models.CharField(blank=True, help_text='Would you prefer to only see plant-based options?', max_length=20, null=True),
        ),
    ]
