# Generated by Django 4.2.9 on 2024-05-26 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profile_dietary_preference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='allergen_preferences',
        ),
        migrations.AddField(
            model_name='profile',
            name='celery',
            field=models.BooleanField(default=False, verbose_name='Celery'),
        ),
        migrations.AddField(
            model_name='profile',
            name='crustaceans',
            field=models.BooleanField(default=False, verbose_name='Crustaceans'),
        ),
        migrations.AddField(
            model_name='profile',
            name='eggs',
            field=models.BooleanField(default=False, verbose_name='Eggs'),
        ),
        migrations.AddField(
            model_name='profile',
            name='fish',
            field=models.BooleanField(default=False, verbose_name='Fish'),
        ),
        migrations.AddField(
            model_name='profile',
            name='gluten',
            field=models.BooleanField(default=False, verbose_name='Gluten'),
        ),
        migrations.AddField(
            model_name='profile',
            name='lupin',
            field=models.BooleanField(default=False, verbose_name='Lupin'),
        ),
        migrations.AddField(
            model_name='profile',
            name='milk',
            field=models.BooleanField(default=False, verbose_name='Milk'),
        ),
        migrations.AddField(
            model_name='profile',
            name='molluscs',
            field=models.BooleanField(default=False, verbose_name='Molluscs'),
        ),
        migrations.AddField(
            model_name='profile',
            name='mustard',
            field=models.BooleanField(default=False, verbose_name='Mustard'),
        ),
        migrations.AddField(
            model_name='profile',
            name='nuts',
            field=models.BooleanField(default=False, verbose_name='Nuts'),
        ),
        migrations.AddField(
            model_name='profile',
            name='peanuts',
            field=models.BooleanField(default=False, verbose_name='Peanuts'),
        ),
        migrations.AddField(
            model_name='profile',
            name='sesame_seeds',
            field=models.BooleanField(default=False, verbose_name='Sesame Seeds'),
        ),
        migrations.AddField(
            model_name='profile',
            name='soybeans',
            field=models.BooleanField(default=False, verbose_name='Soybeans'),
        ),
        migrations.AddField(
            model_name='profile',
            name='sulphur_dioxide_and_sulphites',
            field=models.BooleanField(default=False, verbose_name='Sulphur Dioxide and Sulphites'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='newsletter_recipient',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Allergen',
        ),
    ]
