# Generated by Django 4.2.9 on 2024-06-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_remove_profile_allergen_preferences_profile_celery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionproduct',
            name='description',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
    ]
