# Generated by Django 4.2.9 on 2024-05-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchproduct',
            name='product_type',
            field=models.CharField(blank=True, choices=[('edible', 'Edible'), ('merch', 'Merch'), ('subscription', 'Subscription')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='merchproduct',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='merchproduct',
            name='name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='merchproduct',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
