# Generated by Django 4.2.9 on 2024-05-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='merch_images/'),
        ),
    ]
