# Generated by Django 4.2.9 on 2024-05-21 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0002_merchproduct_product_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchproduct',
            name='text_options',
            field=models.ManyToManyField(blank=True, related_name='merch_products', to='merch.textoption'),
        ),
        migrations.AlterField(
            model_name='textoption',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_option_set', to='merch.merchproduct'),
        ),
    ]
