# Generated by Django 4.2.9 on 2024-05-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0003_textoption_colourvariation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colourvariation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='colour_variations/'),
        ),
    ]
