# Generated by Django 4.2.9 on 2024-05-22 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0003_merchproduct_text_options_alter_textoption_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textoption',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_option', to='merch.merchproduct'),
        ),
    ]
