# Generated by Django 4.2.9 on 2024-06-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0004_alter_textoption_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchproduct',
            name='description',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
    ]
