# Generated by Django 4.2.9 on 2024-05-07 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0004_alter_colourvariation_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchproduct',
            name='colour',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
