# Generated by Django 4.2.9 on 2024-05-07 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0005_merchproduct_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='textoption',
            name='is_default',
            field=models.BooleanField(default=False, help_text='This will be the default phrase for this product'),
        ),
    ]
