# Generated by Django 4.2.9 on 2024-05-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0006_textoption_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colourvariation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='merchproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='textoption',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
