# Generated by Django 4.2.9 on 2024-05-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0007_alter_colourvariation_image_alter_merchproduct_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colourvariation',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
