# Generated by Django 4.2.9 on 2024-05-17 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0008_colourvariation_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colourvariation',
            name='url',
        ),
        migrations.AddField(
            model_name='colourvariation',
            name='url_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='url_products', to='merch.merchproduct'),
        ),
    ]
