# Generated by Django 4.2.9 on 2024-05-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_orderlineitem_subscription_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='product_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
