# Generated by Django 4.2.9 on 2024-05-10 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edible_products', '0010_edibleproduct_name'),
        ('merch', '0006_textoption_is_default'),
        ('checkout', '0005_order_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='product',
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='edible_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='edible_products.edibleproduct'),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='merch_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='merch.merchproduct'),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='product_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
