# Generated by Django 4.2.9 on 2024-05-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_remove_orderlineitem_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dispatched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='made',
            field=models.BooleanField(default=False),
        ),
    ]
