# Generated by Django 4.2.9 on 2024-05-14 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0006_textoption_is_default'),
        ('checkout', '0007_order_dispatched_orderlineitem_made'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='selected_text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='merch.textoption'),
        ),
    ]
