# Generated by Django 4.2.9 on 2024-05-21 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edible_products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edibleproduct',
            name='quantity',
        ),
    ]
