# Generated by Django 4.2.9 on 2024-02-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edible_products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allergen',
            name='description',
        ),
        migrations.RemoveField(
            model_name='allergen',
            name='name',
        ),
        migrations.AddField(
            model_name='allergen',
            name='celery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='allergen',
            name='crustaceans',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='allergen',
            name='eggs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='allergen',
            name='fish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='allergen',
            name='gluten',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='allergen',
            name='lupin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='allergen',
            name='milk',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='allergen',
            name='molluscs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='allergen',
            name='mustard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='allergen',
            name='nuts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='allergen',
            name='peanuts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='allergen',
            name='sesame_seeds',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='allergen',
            name='soybeans',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='allergen',
            name='sulphur_dioxide_and_sulphites',
            field=models.BooleanField(default=False),
        ),
    ]
