# Generated by Django 4.2.9 on 2024-05-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edible_products', '0002_remove_edibleproduct_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edibleproduct',
            name='rating',
        ),
        migrations.AddField(
            model_name='edibleproduct',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='edibleproduct',
            name='product_type',
            field=models.CharField(blank=True, choices=[('edible', 'Edible'), ('merch', 'Merch'), ('subscription', 'Subscription')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='edibleproduct',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='edibleproduct',
            name='name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
