# Generated by Django 4.2.9 on 2024-02-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edible_products', '0002_remove_allergen_description_remove_allergen_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edibleproduct',
            name='allergens',
        ),
        migrations.AddField(
            model_name='edibleproduct',
            name='celery',
            field=models.BooleanField(default=False, verbose_name='Celery'),
        ),
        migrations.AddField(
            model_name='edibleproduct',
            name='crustaceans',
            field=models.BooleanField(default=False, verbose_name='Crustaceans'),
        ),
        migrations.AddField(
            model_name='edibleproduct',
            name='eggs',
            field=models.BooleanField(default=False, verbose_name='Eggs'),
        ),
        migrations.AddField(
            model_name='edibleproduct',
            name='fish',
            field=models.BooleanField(default=False, verbose_name='Fish'),
        ),
        migrations.AddField(
            model_name='edibleproduct',
            name='gluten',
            field=models.BooleanField(default=False, verbose_name='Gluten'),
        ),
        migrations.AddField(
            model_name='edibleproduct',
            name='lupin',
            field=models.BooleanField(default=False, verbose_name='Lupin'),
        ),
        migrations.AddField(
            model_name='edibleproduct',
            name='milk',
            field=models.BooleanField(default=False, verbose_name='Milk'),
        ),
        migrations.AddField(
            model_name='edibleproduct',
            name='molluscs',
            field=models.BooleanField(default=False, verbose_name='Molluscs'),
        ),
        migrations.AddField(
            model_name='edibleproduct',
            name='mustard',
            field=models.BooleanField(default=False, verbose_name='Mustard'),
        ),
        migrations.AddField(
            model_name='edibleproduct',
            name='nuts',
            field=models.BooleanField(default=False, verbose_name='Nuts'),
        ),
        migrations.AddField(
            model_name='edibleproduct',
            name='peanuts',
            field=models.BooleanField(default=False, verbose_name='Peanuts'),
        ),
        migrations.AddField(
            model_name='edibleproduct',
            name='sesame_seeds',
            field=models.BooleanField(default=False, verbose_name='Sesame Seeds'),
        ),
        migrations.AddField(
            model_name='edibleproduct',
            name='soybeans',
            field=models.BooleanField(default=False, verbose_name='Soybeans'),
        ),
        migrations.AddField(
            model_name='edibleproduct',
            name='sulphur_dioxide_and_sulphites',
            field=models.BooleanField(default=False, verbose_name='Sulphur Dioxide and Sulphites'),
        ),
        migrations.DeleteModel(
            name='Allergen',
        ),
    ]
