# Generated by Django 4.2.9 on 2024-05-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edible_products', '0003_remove_edibleproduct_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edibleproduct',
            name='details',
        ),
        migrations.AlterField(
            model_name='edibleproduct',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='edibleproduct',
            name='flavour',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='edibleproduct',
            name='image_url',
            field=models.URLField(max_length=1024, null=True),
        ),
    ]
