# Generated by Django 4.2.9 on 2024-02-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edible_products', '0003_remove_edibleproduct_allergens_edibleproduct_celery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='edibleproduct',
            name='weight',
            field=models.DecimalField(decimal_places=0, default=400, max_digits=4),
        ),
    ]
