# Generated by Django 4.2.9 on 2024-06-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edible_products', '0004_remove_edibleproduct_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergen',
            name='description',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='edibleproduct',
            name='description',
            field=models.TextField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='edibleproduct',
            name='ingredients',
            field=models.TextField(max_length=300),
        ),
    ]
