# Generated by Django 4.2.9 on 2024-02-07 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edible_products', '0004_edibleproduct_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edibleproduct',
            name='weight',
            field=models.DecimalField(decimal_places=0, default=400, help_text='Weight in grams', max_digits=4),
        ),
    ]
