# Generated by Django 4.2.9 on 2024-02-09 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edible_products', '0005_alter_edibleproduct_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductWeightPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight in grams', max_digits=6)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_prices', to='edible_products.edibleproduct')),
            ],
        ),
    ]
