# Generated by Django 4.2.9 on 2024-02-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edible_products', '0006_productweightprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edibleproduct',
            name='weight',
            field=models.PositiveIntegerField(choices=[(100, '100g'), (400, '400g'), (800, '800g')], default=400, help_text='Weight in grams'),
        ),
    ]
