# Generated by Django 4.2.9 on 2024-06-05 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edible_products', '0007_alter_edibleproduct_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edibleproduct',
            name='ingredients',
            field=models.TextField(max_length=700),
        ),
    ]
