# Generated by Django 4.2.9 on 2024-04-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edible_products', '0008_alter_productweightprice_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('symbol', models.ImageField(blank=True, null=True, upload_to='allergens/')),
            ],
        ),
        migrations.AddField(
            model_name='edibleproduct',
            name='allergens',
            field=models.ManyToManyField(blank=True, to='edible_products.allergen'),
        ),
    ]
