# Generated by Django 4.2.9 on 2024-05-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edible_products', '0009_allergen_edibleproduct_allergens'),
    ]

    operations = [
        migrations.AddField(
            model_name='edibleproduct',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
