# Generated by Django 4.2.9 on 2024-05-13 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edible_products', '0010_edibleproduct_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edibleproduct',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
