# Generated by Django 4.2.9 on 2024-05-13 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edible_products', '0011_alter_edibleproduct_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edibleproduct',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
