# Generated by Django 4.2.9 on 2024-05-17 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edible_products', '0012_alter_edibleproduct_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edibleproduct',
            name='image_url',
        ),
    ]
