# Generated by Django 4.2.9 on 2024-05-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edible_products', '0013_remove_edibleproduct_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='edibleproduct',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
