# Generated by Django 4.2.9 on 2024-02-07 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OurStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the page title', max_length=200)),
                ('content', models.TextField(help_text='Enter the page content')),
                ('image', models.ImageField(blank=True, help_text='Upload an image for the story', null=True, upload_to='our_story_images/')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
