# Generated by Django 4.2.9 on 2024-06-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='email',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ourstory',
            name='content',
            field=models.TextField(help_text='Enter the page content', max_length=1000),
        ),
    ]
