# Generated by Django 4.2.9 on 2024-05-16 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_inquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='is_dealt_with',
            field=models.BooleanField(default=False),
        ),
    ]
