# Generated by Django 4.2.9 on 2024-05-17 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_inquiry_is_dealt_with'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourstory',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image for the story', null=True, upload_to=''),
        ),
    ]
